baseURL = "https://vain0x.github.io/blog"
publishDir = "docs"
theme = "beautifulhugo"

title = "ベインのブログ"

languageCode = "ja-jp"
DefaultContentLanguage = "ja"

metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

[[menu.main]]
name = "GitHub"
url = "https://github.com/vain0x"
weight = 1

[[menu.main]]
name = "競プロ参戦記"
url = "https://qiita.com/search?q=競プロ参戦記+user%3Avain0x"
weight = 1

[[menu.main]]
name = "ABOUT"
url = "https://vain0x.github.io"
weight = 1
